name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  rust-ci:
    name: Format, Lint & Test
    uses: UniverLab/workflows/.github/workflows/rust-ci.yml@main
    with:
      system-packages: protobuf-compiler


